### ISSUE TITLE
No way to customize keyboard shortcut or detect conflicts WAS: Keyboard Shortcut Is not Working

### ISSUE THREAD

**Issue by franzalex** [thePaulV/Most-Recent-Tab#1]
According to the description, the default key binding is **`Ctrl+Shift+1`** on Windows systems. Unfortunately this key combination does not trigger any action on my computer. Clicking the button on the toolbar works though. 

Can you please fix this or otherwise allow the user to remap the key binding to a different one?

**EDIT**  
After reading the description in totality, I see you have indicated that the current framework doesn't allow customising keyboard shortcuts. Does this mean that the shortcut you indicated in the add-on's description is non-functional?

**Comment by thePaulV** [comment]
HI @franzalex, that's correct, unfortunately the new API is less flexible than the old one and there's no way to allow for customized keyboard shortcuts until bug [1303384](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384) is fixed by the Firefox team.

In the meantime, I'd suggest seeing if you have any other extensions that have also requested the same shortcut and caused a conflict.

**Comment by equalsJeffH** [comment]
how might one easily "[see] if you have any other extensions that have also requested the same shortcut and caused a conflict" ?  I'm on Mac OS and `command + shift+ 1` is not working :(

**Comment by thePaulV** [comment]
Hi @equalsJeffH, user visibility into extension shortcuts is also part of bug [1303384](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384) so in the meantime it would be about checking the documentation for your other extensions. Once bug [1320332](https://bugzilla.mozilla.org/show_bug.cgi?id=1320332) is fixed I'll be able to do more as the developer as well. Sorry I don't have better news yet, the WebExtensions APIs are still quite new.

**Comment by thePaulV** [comment]
This is resolved in version 2.0 in Firefox 60, thanks to the new commands.update API in Firefox. The addon now has a preferences pane where you can specify a custom shortcut.

**Comment by as3mbus** [comment]
when the version 2 going to be released ? 
i can only download version 1.1

**Comment by thePaulV** [comment]
Hi @as3mbus, Version 2 requires Firefox 60, which is scheduled to come out this week. I'll flip the switch in the addon once that happens.

**Comment by as3mbus** [comment]
ah i see. so that's why. i use nightly so i got confused when you say it's fixed in firefox 60 when i alrdy got nightly with version 62.
cant wait to try it. 
thank you for your awesome work
