### ISSUE TITLE
[Feature request] 2-3 additional history/memory states

### ISSUE THREAD

**Issue by SHHSSH** [thePaulV/Most-Recent-Tab#13]
### Description

This is up there with one of my most used macros, however, what would potentially make it incredible, would be a couple more history/memory states that offer different hotkey macros.

Say for example I use, F10 for the "Most recent tab"
However, in FF shortcuts, the user is offered the option to hotkey a few other states.
E.g; 
F1 - Second most recent tab
F2 - Third most recent tab
F4 - Fourth most recent tab (perhaps unnecessary, perhaps utilised as a placeholder/origin tab backtrack)

Have really loved the productivity of this Add-on.
Thanks.

**Comment by SHHSSH** [comment]
This may be complicated to grasp from a coding aspect, though I believe if you store the original tab from the initial command instantiation, then that becomes the "origin" tab.

**Comment by thePaulV** [comment]
Hi @SHHSSH , version 3.1 implements this idea. It may need some time before the update appears on AMO. Once it's live there, you can force an update by going to the Add-on manager, clicking the gear, and picking "Check for Updates".

By default there are no keys set, you'll have to go to the Add-on manager, click the gear, and select "Manage Extension Shortcuts" to pick your own keyboard shortcuts.

**Comment by SHHSSH** [comment]
Wow, thank you.

**Comment by SHHSSH** [comment]
@thePaulV 

Learning to use the second & third effectively is such a trip, lol.

**Comment by thePaulV** [comment]
@SHHSSH Hah! I can believe it, I tested it a bit and certainly it's a bigger mental jump than just toggling back to the last one. Hopefully you're finding it useful.

**Comment by SHHSSH** [comment]
@thePaulV Paul would you have any tips or suggestions one may find useful when attempting to implement a similar functionality for windows' alt+tab or its variations? I use two things atm, one a mere AHK script for universal desktop application listing, and a second program called "Alt-Tab terminator", which has modifiable settings and only shows the current desktop.

I guess what I'm asking is if perhaps you could imagine this functionality in an operating system too? Or if know of any possibility whereas it has been achieved.

Thanks.

**Comment by SHHSSH** [comment]
Btw, I have thoroughly utilised this feature.

I have macros on my mouse that synergise with it perfectly to where I've muscle-memoried it for its use in FF.
