### ISSUE TITLE
Feature request: Remember more than 1 most recent tab

### ISSUE THREAD

**Issue by neube3** [thePaulV/Most-Recent-Tab#6]
### Description

TMP used to remember the whole queue of active tabs, so having opened and activated tabs A through K and then closing B to J tabs without activating them meant that clicking on the active K tab (which is a blocked-by-webextensions feature request https://github.com/thePaulV/Most-Recent-Tab/issues/2) would switch to tab A.

Most Recent Tab extension does just what it says on the tin. Which, makes it defunct after closing an (inactive) most recent tab, as it breaks the link in the chain; therefore the extension does (not know to which tab it should switch?) not change active tab.

### Steps to Reproduce

1. Open three tabs
2. Activate them all, one by one (A, B, C)
3. Close tab B (e.g. by middle clicking [on Windows]), so only tabs A and C are open
4. Press the extension button or keyboard shortcut if it works for your config [ctrl+shift+1 sadly does not work for the reporter :(]

**Expected behaviour:**
Extension switches from active tab C to previously-most-recent tab A.

**Actual behaviour:**
Extension does not switch tabs.

### Other Information and Versions

* Firefox version: 57.0.4. (64bit) **portable**
* Operating system and version: Windows 8.1

[Any additional information, configuration or data that might be necessary to reproduce the issue.]
I'm running 57 tests from portable because I wanted to try living without TMP, so I cannot reproduce it myself on a full install.

EDIT: Clarity

**Comment by sojusnik** [comment]
This extensions could serve as an inspiration: [TabWalk](https://addons.mozilla.org/de/firefox/addon/tabwalk/), [Cycle Last Tab Used](https://addons.mozilla.org/de/firefox/addon/clut-cycle-last-used-tabs/) (its [GitHub](https://github.com/nikola-kocic/clut-browser-extension))

**Comment by sojusnik** [comment]
Would love to see that too!

It already works in those extensions: [TabWalk](https://addons.mozilla.org/de/firefox/addon/tabwalk/), [Cycle Last Tab Used](https://addons.mozilla.org/de/firefox/addon/clut-cycle-last-used-tabs/) (its [GitHub](https://github.com/nikola-kocic/clut-browser-extension))
But I would prefer to use your extension, because of the option to define a custom shortcut.
