### ISSUE TITLE
Push v2 to addons.mozilla.org

### ISSUE THREAD

**Issue by engelju** [thePaulV/Most-Recent-Tab#7]
### Description

[v2 was released some 17 days ago](https://github.com/thePaulV/Most-Recent-Tab/releases/tag/v2.0).

Yet [AMO](https://addons.mozilla.org/en-US/firefox/addon/most-recent-tab/) still shows only Version 1.1 to be installed.

### Steps to Reproduce

1. Go to https://addons.mozilla.org/en-US/firefox/addon/most-recent-tab/

**Expected behavior:**

Have v2 to be displayed and ready to be installed.

**Actual behavior:** 

Instead v1.1 is shown:

![mrt](https://user-images.githubusercontent.com/2188152/39808096-59160e44-537e-11e8-9868-901526bcb629.png)

**Comment by thePaulV** [comment]
Firefox 60 was released earlier today so I've enabled version 2.
