### ISSUE TITLE
Does not work if new tab is closed, Ctrl+Tab works

### ISSUE THREAD

**Issue by Dreamer8** [thePaulV/Most-Recent-Tab#9]
Hello, I like this extension, thanks for creating it.

### Description

It works good for last two tabs, but when I open a new window and close it, it doesn't work, Ctrl+Tab shortcut works.

### Steps to Reproduce

1. Go to tab 1
2. Go to tab 2
3. Open new tab (tab 3) (new tab, duplicate, or middle click the link at tab 2)
4. Close tab 3
5. Tab 2 is active now
5. Click the button "Most recent tab"

**Expected behavior:** It should switch to tab 1 and then toggle between tab 2 and 1.

**Actual behavior:** Nothing happens, no action.

### When I press Ctrl+Tab shortcut, it works good, so the button should work the same, perhaps just simulate Ctrl+Tab.

* Firefox version: 77.0.1 (64-bit)
* Operating system and version: Windows 10 64-bit 1909
* Most Recent Tab Version 2.0

I had a similar extension, works the same, it has the same issue, I have no contact to author, it's TabToggle by Sriram.

**Comment by craftwar** [comment]
@Dreamer8 
I want to solve the same problem and I find this extension can't do that. I rewrite my own version to handle this.
[https://github.com/craftwar/Last-Used-Tab](https://github.com/craftwar/Last-Used-Tab)

**Comment by Dreamer8** [comment]
> @Dreamer8
> I want to solve the same problem and I find this extension can't do that. I rewrite my own version to handle this.
> https://github.com/craftwar/Last-Used-Tab

Thanks, it looks it works good.

**Comment by thePaulV** [comment]
This is fixed in version 3.0. Closing.
